export const CATEGORY_STYLES = {
  Beef: {
    bg: "bg-red-50",
    text: "text-gray-900",
    border: "border-red-100",
    iconBg: "bg-red-500",
    icon: "fa-solid fa-drumstick-bite",
  },
  Chicken: {
    bg: "bg-orange-50",
    text: "text-gray-900",
    border: "border-orange-100",
    iconBg: "bg-orange-500",
    icon: "fa-solid fa-drumstick-bite",
  },
  Dessert: {
    bg: "bg-pink-50",
    text: "text-gray-900",
    border: "border-pink-100",
    iconBg: "bg-pink-500",
    icon: "fa-solid fa-cake-candles",
  },
  Lamb: {
    bg: "bg-amber-50",
    text: "text-gray-900",
    border: "border-amber-100",
    iconBg: "bg-amber-500",
    icon: "fa-solid fa-bone",
  },
  Miscellaneous: {
    bg: "bg-indigo-50",
    text: "text-gray-900",
    border: "border-indigo-100",
    iconBg: "bg-indigo-500",
    icon: "fa-solid fa-bowl-food",
  },
  Pasta: {
    bg: "bg-yellow-50",
    text: "text-gray-900",
    border: "border-yellow-100",
    iconBg: "bg-yellow-500",
    icon: "fa-solid fa-plate-wheat",
  },
  Pork: {
    bg: "bg-rose-50",
    text: "text-gray-900",
    border: "border-rose-100",
    iconBg: "bg-rose-500",
    icon: "fa-solid fa-bacon",
  },
  Seafood: {
    bg: "bg-sky-50",
    text: "text-gray-900",
    border: "border-sky-100",
    iconBg: "bg-sky-500",
    icon: "fa-solid fa-fish",
  },
  Side: {
    bg: "bg-emerald-50",
    text: "text-gray-900",
    border: "border-emerald-100",
    iconBg: "bg-emerald-500",
    icon: "fa-solid fa-leaf",
  },
  Starter: {
    bg: "bg-teal-50",
    text: "text-gray-900",
    border: "border-teal-100",
    iconBg: "bg-teal-500",
    icon: "fa-solid fa-utensils",
  },
  Vegan: {
    bg: "bg-green-50",
    text: "text-gray-900",
    border: "border-green-100",
    iconBg: "bg-green-500",
    icon: "fa-solid fa-seedling",
  },
  Vegetarian: {
    bg: "bg-lime-50",
    text: "text-gray-900",
    border: "border-lime-100",
    iconBg: "bg-lime-500",
    icon: "fa-solid fa-carrot",
  },
  Breakfast: {
    bg: "bg-orange-50",
    text: "text-gray-900",
    border: "border-orange-100",
    iconBg: "bg-orange-500",
    icon: "fa-solid fa-egg",
  },
  Goat: {
    bg: "bg-stone-50",
    text: "text-gray-900",
    border: "border-stone-100",
    iconBg: "bg-stone-500",
    icon: "fa-solid fa-paw",
  },
};

export const SCANNER_CATEGORIES = [
  {
    name: "Breakfast Cereals",
    icon: "fa-solid fa-bowl-food",
    color: "bg-orange-500",
  },
  { name: "Beverages", icon: "fa-solid fa-glass-water", color: "bg-blue-500" },
  { name: "Snacks", icon: "fa-solid fa-cookie-bite", color: "bg-purple-500" },
  {
    name: "Dairy Products",
    icon: "fa-solid fa-bottle-water",
    color: "bg-sky-500",
  },
  { name: "Fruits", icon: "fa-solid fa-apple-whole", color: "bg-pink-500" },
  { name: "Vegetables", icon: "fa-solid fa-carrot", color: "bg-green-500" },
  { name: "Breads", icon: "fa-solid fa-bread-slice", color: "bg-yellow-500" },
  { name: "Meats", icon: "fa-solid fa-drumstick-bite", color: "bg-red-500" },
];
